sap.ui.define([
    'jquery.sap.global',
    "sap/m/MessageToast"
], function(jQuery,MessageToast) {
    "use strict";
    return {   
        modelDocNuevo: function(){
            var oData = {
                "codAmbiente":"",
                "opcAmbiente":"",
                //////Inicio Roy Tipo Documento//////////////////////
                //////Ocultar Campos/////////////////////////////////
                "ResultVisita":window.dataIni.person.Uname =='SERV_PROV' ? true:false,
                "tituloTabStockDisp":false,
                "tituloTabStockSeparado":false,
                "validCmbOpcionAmbiente":true,
                "OcultarCampos": window.dataIni.person.CanalDist=='10' ? false: false,
                "OcultarCertificado": window.dataIni.person.CanalDist=='10' ? true: false,
                "btnStock":true,
                "ocultarTipoVisita":false,
                "menuMaster":{
                    listPanelDatos:true,
                    listPanelFacturacion:true,
                    listPanelDatosVisita:true,
                    listPanelDatosInstalacion:true,
                    listPanelPedidosAsociados:true,
                    listPanelDatosServicio:true
                },
                "listaMaterialKit":[],
                "valueProfesional":true,
                "visibleCombTipoVisita":false,
                //////Observaciones//////////////////////////////////
                "ObsAtencion":window.dataIni.person.CanalDist=='10' ? true: (window.dataIni.person.CanalDist== '40'? true:true ),
                "ObsRefDire":window.dataIni.person.CanalDist=='10' ? true: (window.dataIni.person.CanalDist== '40'? true:true ),
                "ObsAdm":window.dataIni.person.CanalDist=='10' ? false: (window.dataIni.person.CanalDist== '40'? false:true ),
                "ObsRefFac":window.dataIni.person.CanalDist=='10' ? false: (window.dataIni.person.CanalDist== '40'? false:true ),
                /////////////////////////////////////////////////////
                /////////////////////////////////////////////////////
                /////Grupo Forecast//////////////////////////////////
                "GrupoForeAction": window.dataIni.person.CanalDist=='10' ? false: (window.dataIni.person.CanalDist== '20'? false:true ),
                "TipoForeAction": window.dataIni.person.CanalDist=='10' ? false: (window.dataIni.person.CanalDist== '20'? false:true ),
                ////////////////////////////////////////////////////
                "tipoDocEscogido":"",
                "tituloDocumento":"",
                "NumeroDocumentoReferencia":window.numeroDocumento==false?"":window.numeroDocumento,
                "listaLinea":[{
                    "Codigo": "",
                    "Descripcion": ""
                }],
                
                "listaMarca":[{
                    "Codigo": "",
                    "Descripcion": ""
                }],

                "listacaract":{},
                "documentoNuevo":{
                    "Codigo": "",
                    "Descripcion": "",
                    "Flag1": "",
                    "Flag2": "",
                    "Flag3": "",
                    "Flag4": ""
                },
                //////End Roy Tipo Documento//////////////////////
                "pedido": {
                    "validInterlocutores":true,
                    "enabled": true,
                    "enabledBtnGuardar": true,
                    "enabledBtnCopiar": true,
                    "enabledBtnBuscar": true,
                    "id": "",
                    "CodTipoDoc": "",
                    "CodTipoDocAnt": "",
                    "DocOriginal": "bj",
                    "Referencia": "",  
                    "OrgVentas": "",
                    "CanalDist": "",
                    "CodOficina": "",
                    "CodGrupoVend": "",
                    "CondPago": "",
                    "CodigoBanco": "",
                    "BloqueoEntrega": "",
                    "BloqueoFactura": "",
                    "OrdenCompra": "",
                    "CondExp": "",
                    "FechaPedido": "",
                    "FechaPrecio": "",
                    "FechaValidez": "",
                    "FechaEntrega": "",
                    "FechaResult": "",  
                    "FechaVisita": "",
                    "FechaFacturacion": "", 
                    "nomProyecto": "",
                    "codProyecto": "",
                    "codVersion": "",
                    "TipoVisita": "",
                    "Reenbolsable": false,
                    "GrupoForecast": "",
                    "TipoForecast": "",
                    "Motivo": "",   
                    "Certificado": "",
                    "Percepcion": "",
                    "Sector": "",
                    "Sociedad": "",
                    "PesoTotal": "",  
                    "Moneda": "",
                    "TipoCambio": "",   
                    "Igv": "",  
                    "SubTotal": "",
                    "SubtotalImp": "",
                    "Total": "",
                    "TotalConIgv": "",
                    "TotalDcto": "",
                    "TotalImp": "",
                    "CodVendedorWeb": "",
                    "NomVendedorWeb": "",
                    "codigoCliente": "",
                    "GrupoCond": "",
                    "NoImpFac": "",
                    "NumPedido": "",
                    "dsctoAdicionalZD12": "",
                    "dsctoAdicionalZD12tmp": "",
                    "Zasensor": false,
                    "Zncservicio": false,
                    "Znpiso": "",
                    "Ztransporte": ""                                      
                },
                "observaciones": {
                    "ZP01": {
                        "CodTexto": "ZP01",
                        "Descripcion": ""
                    },
                    "ZP05": {
                        "CodTexto": "ZP05",
                        "Descripcion": ""
                    },
                    "ZP06": {
                        "CodTexto": "ZP06",
                        "Descripcion": ""
                    },
                    "ZP07": {
                        "CodTexto": "ZP07",
                        "Descripcion": ""
                    },
                    "ZP09": {
                        "CodTexto": "ZP09",
                        "Descripcion": ""
                    },
                    "ZP10": {
                        "CodTexto": "ZP10",
                        "Descripcion": ""
                    },
                    "ZP11": {
                        "CodTexto": "ZP11",
                        "Descripcion": ""
                    },
                    "ZP12": {
                        "CodTexto": "ZP12",
                        "Descripcion": ""
                    },
                    "ZP13": {
                        "CodTexto": "ZP13",
                        "Descripcion": ""
                    },
                    "ZP14": {
                        "CodTexto": "ZP14",
                        "Descripcion": ""
                    }
                },
                "interlocutores": {
                    "AG": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "CodigoPostal": "",
                            "Distrito": "",                            
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                            
                            "Telefono": "-",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "AG",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },
                    "RE": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "CodigoPostal": "",
                            "Distrito": "",                            
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "RE",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },
                    "RG": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "CodigoPostal": "",
                            "Distrito": "",                            
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "RG",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },
                    "WE": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "CodigoPostal": "",
                            "Distrito": "",                            
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "-",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "WE",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },                    
                    "VE": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "CodigoPostal": "",
                            "Distrito": "",                            
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "VE",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },
                    "V2": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "Distrito": "",                            
                            "CodigoPostal": "",
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "V2",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },
                    "V3": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "Distrito": "",                            
                            "CodigoPostal": "",
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "V3",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },
                    "V4": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "Distrito": "",                            
                            "CodigoPostal": "",
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "V4",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },                    
                    "Z2": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "Distrito": "",                            
                            "CodigoPostal": "",
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "NOMBRE": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "Z2",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },
                    "Z3": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "Distrito": "",                            
                            "CodigoPostal": "",
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "NOMBRE": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "Z3",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    },  
                    "Z5": {
                        "Cliente": {
                            "Ciudad": "",
                            "Codigo": "",
                            "Distrito": "",                            
                            "CodigoPostal": "",
                            "Descripcion": "",
                            "Direccion": "",
                            "DireccionCompleta": "",
                            "Mail": "",
                            "NOMBRE": "",
                            "Pais": "",
                            "Ruc": "",
                            "PersonaFisica": false,
                            "Eventual": false,                              
                            "Telefono": "",
                            "TelefonoMovil": ""
                        },
                        "Funcion": "Z5",
                        "Persona": {
                            "ApeSoltero": "",
                            "Apellido": "",
                            "CodPersona": "",
                            "Descripcion": "",
                            "Dni": "",
                            "Nombre": "",
                            "Telefono": ""
                        }
                    }                                      
                },
                "cliente": {
                    "APMAT": "",
                    "APPAT": "",
                    "CODIG": "",
                    "Codigo": "",
                    "Ciudad": "",
                    "CodigoPostal": "",
                    "DIREC": "",
                    "EDAD": "",
                    "RANGOED": "",
                    "FECNAC": "",
                    "GRAINS": "",
                    "NIVELSE" : "",
                    "Mail": "",
                    "NOMBRE": "",
                    "Pais": "",
                    "Ruc": null,
                    "PersonaFisica": false,
                    "Eventual": false,                      
                    "SEXO": "",
                    "Telefono": "",
                    "TelefonoMovil": null
                },
                "clienteEventual": {
                    "codigoCliente": "", 
                    "nombreCliente": "", 
                    "esEventual": true, 
                },
                "preguntas": {
                    "1": {
                        "CODP": "1",
                        "CODR": ""
                    },
                    "10": {
                        "CODP": "10",
                        "CODR": ""
                    },
                    "15": {
                        "CODP": "15",
                        "CODR": ""
                    },
                    "20": {
                        "CODP": "20",
                        "CODR": ""
                    },
                    "25": {
                        "CODP": "25",
                        "CODR": ""
                    },
                    "35": {
                        "CODP": "35",
                        "CODR": ""
                    }
                },
                "listaMaterial": [{
                        "PrecConIgv":"",
                        "Posicion": "",
                        "PosicionCorto": "",                        
                        "CodMaterial": "",
                        "CodMaterialCorto": "",
                        "DescMaterial": "",
                        "Cantidad": null,
                        "CantConfirmada": null,
                        "CodUMedida": "",
                        "Rendimiento": "",
                        "UMedidaRendimiendo": "",
                        "ValorRendimiento": null,
                        "CodAlmacen": "",
                        "CodCentro": "",
                        "CodLote": "",
                        "DescCentro": "",
                        "DescAlmacen": "",
                        "Zservicio": false,
                        "Peso": null,
                        "PesoNeto": null,
                        "PrecioUnitario": null,
                        "DesGrupoMat": "",
                        "SubTotal": null,
                        "Reparto": "",
                        "Ambiente": "",
                        "Opcion": "",
                        "MotivoRechazo": "",
                        "PrioridadEntrega": "",
                        "Descontinuado": "",
                        "StockPos": "",
                        "JerarquiaPrincipalDesc": "",
                        "link": null,
                        "DescMovil": "",
                        "Descripcion": "",
                        "EsEstiba": false,
                        "EsFlete": false,
                        "EspecialServ": false,
                        "jerarquia": "",
                        "MSTAE": "",
                        "PrecioUnit": null,
                        "Stock": null,
                        "StockTotal": null,
                        "TieneServ": false,
                        "Tipo": "",
                        "TipoMaterial": "",  
                        "PrecioTotal": null,
                        "PrecioUnitario": null,
                        "IgvUnitario": null,
                        "IgvTotal": null,
                        "TotalDctos": null,
                        "SubTotal": null,
                        "TotPercep": "",
                        "SubTotalLista": null,
                        "ConversionUMedida":"",
                        "DivisionRendimiento":null,
                        "DsctoMontTotal":null,
                        "Peso":null,
                        "PrecioConIGV":null,
                        "PrecioSinIGV":null,
                        "Total":null,
                        "TotalImpresion":null,  
                        "TipoPosAnt": "", 
                        "Vdscto": 0,                     
                        "Repartos": [{
                                "CantConf": null,
                                "CantPed": null,
                                "CodUMedida": null,
                                "FechaEntrega": "",
                                "Pos": "",
                                "PosCorto": "",
                                "TipoReparto": "",
                                "matPosicion":""
                            }],
                        "DescuentoPrincipal": [{
                                "Condicion": "",
                                "Denominacion": "",
                                "Importe": null,
                                "ImporteAnterior": null,
                                "LimiteInferior": null,
                                "Moneda": null,
                                "Posicion": "",
                                "Recalcular": "",
                                "Valor": null,
                                "esPorcentaje": true,
                                "matPosicion": ""
                            }],
                        "DescuentoOtros": [{
                                "Condicion": "",
                                "Denominacion": "",
                                "Importe": null,
                                "ImporteAnterior": null,
                                "LimiteInferior": null,
                                "Moneda": null,
                                "Posicion": "",
                                "Recalcular": "",
                                "Valor": null,
                                "esPorcentaje": true,
                                "matPosicion": ""
                            }],
                        "stockDetallado" : [{
                                "CodAlmacen":"",
                                "CodCentro":"",
                                "CodLote":"",
                                "CodMaterial":"",
                                "DescAlmacen":"",
                                "DescCentro":"",
                                "DescDisp":"",
                                "DescMaterial":"",
                                "FechaStock":"",
                                "StockDisponible":null,
                                "StockLibre":null,
                                "ValorCaracteristica":""
                        }]
                    }],
                "busquedaCliente": {
                    "dniRuc": "",
                    "razonSocial": "",
                    "tipoInterlocutor": "",
                    "copiarDatos": false
                },
                "planFacturacion":[{
                            "AFDAT": "",
                            "BONBA": 0,
                            "CCACT": "",
                            "CMPRE": 0,
                            "CMPRE_FLT": 0,
                            "FAKCA": "",
                            "FAKSP": "",
                            "FAKWR": 0,
                            "FAREG": "",
                            "FKARV": "",
                            "FKDAT": "",
                            "FKSAF": "",
                            "FPFIX": "",
                            "FPLAE": "",
                            "FPLNR": "",
                            "FPLTR": "",
                            "FPROZ": 0,
                            "FPTTP": "",
                            "KORTE": "",
                            "KUNRG": "",
                            "KURFP": 0,
                            "KURRF": 0,
                            "KZWI1": 0,
                            "KZWI2": 0,
                            "KZWI3": 0,
                            "KZWI4": 0,
                            "KZWI5": 0,
                            "KZWI6": 0,
                            "MLBEZ": "",
                            "MLSTN": "",
                            "NETPR": 0,
                            "NETWR": 0,
                            "NFDAT": null,
                            "OFKDAT": null,
                            "PERIO": "",
                            "PRSOK": "",
                            "SKFBP": 0,
                            "TAXK1": "",
                            "TAXK2": "",
                            "TAXK3": "",
                            "TAXK4": "",
                            "TAXK5": "",
                            "TAXK6": "",
                            "TAXK7": "",
                            "TAXK8": "",
                            "TAXK9": "",
                            "TEMAN": "",
                            "TETXT": "",
                            "TYPZM": "",
                            "UELNR": "",
                            "UELTR": "",
                            "VALDT": null,
                            "VALTG": "",
                            "WAERS": "",
                            "WAVWR": 0,
                            "ZTERM": ""
                }],

                  "visita":
                {
                    "textoContacto":"",
                    "textoDatosAdicionalesCliente":"",
                    "textoTelefonos":"",
                    "textoDescripcionVisita":"",
                    "textoResultadoVisita":"",
                }
                
            };
            return oData;
        },
        unidadMedida:function(){
            var unidMedida =[
                {"codigo": "", "descripcion": ""},
                {"codigo": "%", "descripcion": "Porcentaje"},
                {"codigo": "%O", "descripcion": "Tanto por mil"},
                {"codigo": "UNO", "descripcion": "Lim."},
                {"codigo": "D", "descripcion": "Días"},
                {"codigo": "22S", "descripcion": "Milímetro cuadrado/Segundo"},
                {"codigo": "CMS", "descripcion": "Centímetro/Segundo"},
                {"codigo": "000", "descripcion": "Metro/Minuto"},
                {"codigo": "µL", "descripcion": "Microlitro"},
                {"codigo": "µF", "descripcion": "Microfaradio"},
                {"codigo": "PF", "descripcion": "Picofaradio"},
                {"codigo": "A", "descripcion": "Amperio"},
                {"codigo": "GOH", "descripcion": "Gigaohmio"},
                {"codigo": "GM3", "descripcion": "Gramo/Metro cúbico"},
                {"codigo": "ACR", "descripcion": "Acre"},
                {"codigo": "KD3", "descripcion": "Kilogramo/Decímetro cúbico"},
                {"codigo": "KML", "descripcion": "Kilomol"},
                {"codigo": "KN", "descripcion": "Kilonewton"},
                {"codigo": "MN", "descripcion": "Meganewton"},
                {"codigo": "MGO", "descripcion": "Megaohmio"},
                {"codigo": "NMP", "descripcion": "Megavoltio"},
                {"codigo": "µA", "descripcion": "Microamperio"},
                {"codigo": "BOL", "descripcion": "Bolsa"},
                {"codigo": "BAR", "descripcion": "bar"},
                {"codigo": "LC", "descripcion": "Botella"},
                {"codigo": "BQ", "descripcion": "Becquerel/Kilogramo"},
                {"codigo": "CO", "descripcion": "Milifaradio"},
                {"codigo": "M/M", "descripcion": "Mol por metro cúbico"},
                {"codigo": "M/L", "descripcion": "Mol por litro"},
                {"codigo": "NR", "descripcion": "Nanoamperio"},
                {"codigo": "C3S", "descripcion": "Centímetro cúbico/Segundo"},
                {"codigo": "NF", "descripcion": "Nanofaradio"},
                {"codigo": "NMM", "descripcion": "Newton/Milímetro cuadrado"},
                {"codigo": "CA1", "descripcion": "CAJA 1"},
                {"codigo": "CM3", "descripcion": "Centímetro cúbico"},
                {"codigo": "CD", "descripcion": "Candela"},
                {"codigo": "DM3", "descripcion": "Decímetro cúbico"},
                {"codigo": "CM", "descripcion": "Centímetros"},
                {"codigo": "CM2", "descripcion": "Centímetro cuadrado"},
                {"codigo": "CMH", "descripcion": "Centímetro/Hora"},
                {"codigo": "CJ", "descripcion": "Caja"},
                {"codigo": "CL", "descripcion": "Centilitro"},
                {"codigo": "S/M", "descripcion": "Siemens por metro"},
                {"codigo": "TOM", "descripcion": "Tonelada/Metro cúbico"},
                {"codigo": "VA", "descripcion": "Voltioamperio"},
                {"codigo": "DEG", "descripcion": "Grado"},
                {"codigo": "DM", "descripcion": "Decímetro"},
                {"codigo": "TR", "descripcion": "Tambor"},
                {"codigo": "DOC", "descripcion": "Docena"},
                {"codigo": "C/U", "descripcion": "cada uno"},
                {"codigo": "RS", "descripcion": "Unidades enzimas"},
                {"codigo": "EML", "descripcion": "Unidades enzimas/Milímetro"},
                {"codigo": "F", "descripcion": "Faradio"},
                {"codigo": "°F", "descripcion": "Fahrenheit"},
                {"codigo": "TF", "descripcion": "Pie"},
                {"codigo": "PI2", "descripcion": "Pie cuadrado"},
                {"codigo": "PI3", "descripcion": "Pie cúbico"},
                {"codigo": "G", "descripcion": "Gramo"},
                {"codigo": "G/L", "descripcion": "Gramo aditivo/Litro"},
                {"codigo": "GAU", "descripcion": "Gramo oro"},
                {"codigo": "°C", "descripcion": "Grado centígrado"},
                {"codigo": "GHG", "descripcion": "Gramo/Hectogramo"},
                {"codigo": "GJ", "descripcion": "Gigajulio"},
                {"codigo": "GKG", "descripcion": "Gramo/Kilogramo"},
                {"codigo": "GLI", "descripcion": "Gramo/Litro"},
                {"codigo": "GLN", "descripcion": "Galón (EE.UU.)"},
                {"codigo": "GPM", "descripcion": "Galones por milla (EE.UU)"},
                {"codigo": "GM", "descripcion": "Gramo/Mol"},
                {"codigo": "GM2", "descripcion": "Gramo/Metro cuadrado"},
                {"codigo": "GPH", "descripcion": "Galones por hora (EE.UU)"},
                {"codigo": "µGV", "descripcion": "Microgramo/Metro cúbico"},
                {"codigo": "GRD", "descripcion": "Grande"},
                {"codigo": "GPA", "descripcion": "Gramo principio activo"},
                {"codigo": "H", "descripcion": "Hora"},
                {"codigo": "HA", "descripcion": "Hectárea"},
                {"codigo": "HL", "descripcion": "Hectolitro"},
                {"codigo": "HPA", "descripcion": "Hectopascal"},
                {"codigo": "HZ", "descripcion": "Hercio (1/segundo)"},
                {"codigo": "PUL", "descripcion": "Pulgada"},
                {"codigo": "2", "descripcion": "Pulgada cuadrada"},
                {"codigo": "3", "descripcion": "Pulgada cúbica"},
                {"codigo": "J", "descripcion": "Julio"},
                {"codigo": "JHR", "descripcion": "Años (annum)"},
                {"codigo": "JKG", "descripcion": "Julio/Kilogramo"},
                {"codigo": "JKK", "descripcion": "Capac.térmica espec."},
                {"codigo": "JMO", "descripcion": "Julio/Mol"},
                {"codigo": "K", "descripcion": "Kelvin"},
                {"codigo": "KA", "descripcion": "Kiloamperio"},
                {"codigo": "BID", "descripcion": "Bidón"},
                {"codigo": "CAR", "descripcion": "Cartón"},
                {"codigo": "KBL", "descripcion": "Kilobecquerel/Kilogramo"},
                {"codigo": "KG", "descripcion": "Kilogramo"},
                {"codigo": "KGF", "descripcion": "Kilogramo/Metro cuadrado"},
                {"codigo": "KGK", "descripcion": "Kilogramo/Kilogramo"},
                {"codigo": "KGM", "descripcion": "Kilogramo/Mol"},
                {"codigo": "KGS", "descripcion": "Kilogramo/Segundo"},
                {"codigo": "KGV", "descripcion": "Kilogramo/Metro cúbico"},
                {"codigo": "KGP", "descripcion": "Kilogramo principio activo"},
                {"codigo": "KHZ", "descripcion": "Kilohercio"},
                {"codigo": "CA", "descripcion": "Caja"},
                {"codigo": "KJ", "descripcion": "Kilojulio"},
                {"codigo": "KJK", "descripcion": "Kilojulio/Kilogramo"},
                {"codigo": "KJM", "descripcion": "Kilojulio/Mol"},
                {"codigo": "KM", "descripcion": "Kilómetro"},
                {"codigo": "KM2", "descripcion": "Kilómetro cuadrado"},
                {"codigo": "KMH", "descripcion": "Kilómetro/Hora"},
                {"codigo": "KMK", "descripcion": "Metro cúbico/Metro cúbico"},
                {"codigo": "KMN", "descripcion": "Kelvin/Minuto"},
                {"codigo": "KMS", "descripcion": "Kelvin/Segundo"},
                {"codigo": "KOH", "descripcion": "Kiloohmio"},
                {"codigo": "KPA", "descripcion": "Kilopascal"},
                {"codigo": "KT", "descripcion": "Kilotoneladas"},
                {"codigo": "KV", "descripcion": "Kilovoltio"},
                {"codigo": "KVA", "descripcion": "Kilovoltioamperio"},
                {"codigo": "KW", "descripcion": "Kilovatio"},
                {"codigo": "KWH", "descripcion": "Kilovatio-hora"},
                {"codigo": "KWK", "descripcion": "Kg principio activo/kg"},
                {"codigo": "L", "descripcion": "Litro"},
                {"codigo": "LMI", "descripcion": "Litro/Minuto"},
                {"codigo": "LB", "descripcion": "Libra (pound)"},
                {"codigo": "UP", "descripcion": "Unidad de potencia"},
                {"codigo": "LCK", "descripcion": "Litro por 100 km"},
                {"codigo": "LMS", "descripcion": "Litro/Molécula-segundo"},
                {"codigo": "LPH", "descripcion": "Litro por hora"},
                {"codigo": "M", "descripcion": "Metro"},
                {"codigo": "M%", "descripcion": "Porcentaje-masa"},
                {"codigo": "M%O", "descripcion": "Tanto por mil-masa"},
                {"codigo": "M/S", "descripcion": "Metro/Segundo"},
                {"codigo": "M2", "descripcion": "Metro cuadrado"},
                {"codigo": "M-2", "descripcion": "1 / Metro cuadrado"},
                {"codigo": "M2S", "descripcion": "Metro cuadrado/Segundo"},
                {"codigo": "M3", "descripcion": "Metro cúbico"},
                {"codigo": "M3S", "descripcion": "Metro cúbico/Segundo"},
                {"codigo": "MA", "descripcion": "Miliamperio"},
                {"codigo": "MBA", "descripcion": "Milibar"},
                {"codigo": "MBT", "descripcion": "Metrobaro/Segundo"},
                {"codigo": "MEJ", "descripcion": "Megajulio"},
                {"codigo": "MG", "descripcion": "Miligramo"},
                {"codigo": "MGS", "descripcion": "Miligramo/Centímetro cuadrado"},
                {"codigo": "MGG", "descripcion": "Miligramo/Gramo"},
                {"codigo": "MGK", "descripcion": "Miligramo/Kilogramo"},
                {"codigo": "MGL", "descripcion": "Miligramo/Litro"},
                {"codigo": "MGV", "descripcion": "Miligramo/Metro cúbico"},
                {"codigo": "MGW", "descripcion": "Megavatio"},
                {"codigo": "MHZ", "descripcion": "Megahercio"},
                {"codigo": "MI", "descripcion": "Milla"},
                {"codigo": "MI2", "descripcion": "Milla cuadrada"},
                {"codigo": "µM", "descripcion": "Micrometro"},
                {"codigo": "MIN", "descripcion": "Minuto"},
                {"codigo": "MIS", "descripcion": "Microsegundo"},
                {"codigo": "MJ", "descripcion": "Milijulio"},
                {"codigo": "ML", "descripcion": "Mililitro"},
                {"codigo": "MLS", "descripcion": "Mililitro/Metro cúbico"},
                {"codigo": "MLW", "descripcion": "Milílitro principio activo"},
                {"codigo": "MM", "descripcion": "Milímetro"},
                {"codigo": "MM2", "descripcion": "Milímetro cuadrado"},
                {"codigo": "MMA", "descripcion": "Milímetro/Año"},
                {"codigo": "MMG", "descripcion": "Milimol/Gramo"},
                {"codigo": "MMH", "descripcion": "Milímetro/Hora"},
                {"codigo": "MMK", "descripcion": "Milimol/Kilogramo"},
                {"codigo": "MMO", "descripcion": "Milimol"},
                {"codigo": "MM3", "descripcion": "Milímetro cúbico"},
                {"codigo": "MMS", "descripcion": "Milímetro/Segundo"},
                {"codigo": "MNM", "descripcion": "Milinewton/Metro"},
                {"codigo": "MOK", "descripcion": "Mol/Kilogramo"},
                {"codigo": "MOL", "descripcion": "Mol"},
                {"codigo": "MON", "descripcion": "Meses"},
                {"codigo": "MPA", "descripcion": "Megapascal"},
                {"codigo": "MPB", "descripcion": "Partes por billón (masa)"},
                {"codigo": "MLG", "descripcion": "Millas por galón (EEUU)"},
                {"codigo": "MPM", "descripcion": "Partes por millón (masa)"},
                {"codigo": "MPS", "descripcion": "Milipascal por segundo"},
                {"codigo": "MPT", "descripcion": "Partes por trillón (masa)"},
                {"codigo": "MPZ", "descripcion": "Metropascal/Segundo"},
                {"codigo": "M3H", "descripcion": "Metro cúbico/Hora"},
                {"codigo": "MS", "descripcion": "Milisegundo"},
                {"codigo": "MS2", "descripcion": "Metro/Segundo al cuadrado"},
                {"codigo": "MTE", "descripcion": "Militesla"},
                {"codigo": "MH", "descripcion": "Metro/Hora"},
                {"codigo": "MV", "descripcion": "Milivoltio"},
                {"codigo": "MVA", "descripcion": "Megavoltioamperio"},
                {"codigo": "MW", "descripcion": "Milivatio"},
                {"codigo": "MWH", "descripcion": "Megavatio/Hora"},
                {"codigo": "N", "descripcion": "Newton"},
                {"codigo": "NAM", "descripcion": "Nanometro"},
                {"codigo": "N/M", "descripcion": "Newton/Metro"},
                {"codigo": "NS", "descripcion": "Nanosegundo"},
                {"codigo": "OCM", "descripcion": "Resistencia eléctrica espec."},
                {"codigo": "OHM", "descripcion": "Ohmio"},
                {"codigo": "AA", "descripcion": "Resistencia eléctrica espec."},
                {"codigo": "OZ", "descripcion": "Onza"},
                {"codigo": "OZL", "descripcion": "Onza líquida EE.UU."},
                {"codigo": "P", "descripcion": "Puntos"},
                {"codigo": "PA", "descripcion": "Pascal"},
                {"codigo": "PAA", "descripcion": "Par"},
                {"codigo": "BTO", "descripcion": "Bulto"},
                {"codigo": "PAL", "descripcion": "Paleta"},
                {"codigo": "PAS", "descripcion": "Pascal-segundo"},
                {"codigo": "CEB", "descripcion": "Participación en grupo en %"},
                {"codigo": "PMI", "descripcion": "1/minuto"},
                {"codigo": "PMR", "descripcion": "Grado de permeación SI"},
                {"codigo": "PPB", "descripcion": "Partes por billón"},
                {"codigo": "PPM", "descripcion": "Parts per million"},
                {"codigo": "PPT", "descripcion": "Partes por trillón"},
                {"codigo": "PRM", "descripcion": "Grado de permeación"},
                {"codigo": "PRS", "descripcion": "Número de personas"},
                {"codigo": "PS", "descripcion": "Picosegundo"},
                {"codigo": "PT", "descripcion": "Pinta EE.UU., líquido"},
                {"codigo": "PZA", "descripcion": "Pieza"},
                {"codigo": "CTO", "descripcion": "Cuarto galón, EE.UU., líquido"},
                {"codigo": "RHO", "descripcion": "Gramos/Centímetro cúbico"},
                {"codigo": "ROL", "descripcion": "Rollos"},
                {"codigo": "S", "descripcion": "Segundo"},
                {"codigo": "UN", "descripcion": "Unidad"},
                {"codigo": "HRA", "descripcion": "Horas"},
                {"codigo": "DÍA", "descripcion": "Días"},
                {"codigo": "TC1", "descripcion": "Toceto 10X15"},
                {"codigo": "TC2", "descripcion": "Toceto 30X30"},
                {"codigo": "TC3", "descripcion": "1/centímetro cúbico"},
                {"codigo": "TES", "descripcion": "Tesla"},
                {"codigo": "TS", "descripcion": "Miles"},
                {"codigo": "TM3", "descripcion": "1/metro cúbico"},
                {"codigo": "T", "descripcion": "Tonelada"},
                {"codigo": "TON", "descripcion": "Tonelada EE.UU."},
                //{"codigo": "001"}, 
                {"codigo": "µGL", "descripcion": "Microgramo/Litro"},
                //{"codigo": "uni "},
                {"codigo": "V", "descripcion": "Voltio"},
                {"codigo": "V%", "descripcion": "Porcentaje en volumen"},
                {"codigo": "V%O", "descripcion": "Volumen por mil"},
                {"codigo": "MSC", "descripcion": "Microsiemens por centímetro"},
                {"codigo": "MLF", "descripcion": "Millimol por litro"},
                {"codigo": "VAL", "descripcion": "Artículo de valor"},
                {"codigo": "VPB", "descripcion": "Partes de volumen por billón"},
                {"codigo": "VPM", "descripcion": "Partes de volumen por millón"},
                {"codigo": "VPT", "descripcion": "Partes de volumen por trillón"},
                {"codigo": "W", "descripcion": "Vatios"},
                {"codigo": "WCH", "descripcion": "Semanas"},
                {"codigo": "WMK", "descripcion": "Conductibilidad del calor"},
                {"codigo": "WTL", "descripcion": "Velocidad de evaporación"},
                {"codigo": "YD", "descripcion": "Yarda"},
                {"codigo": "YD2", "descripcion": "Yarda cuadrada"},
                {"codigo": "YD3", "descripcion": "Yarda cúbica"}
                ];

                return unidMedida;
        }
    };
});